# Generated by Django 5.0.7 on 2024-07-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeManager', '0002_remove_recipe_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('dessert', 'Dessert')], default='dinner', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dietary_preferences',
            field=models.CharField(choices=[('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('gluten_free', 'Gluten-Free'), ('seafood', 'Seafood'), ('non_vegetarian', 'Non-Vegetarian')], default='vegan', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=50),
        ),
    ]
