# Generated by Django 5.0.7 on 2024-07-17 23:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeManager', '0005_alter_recipe_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('user', 'name')},
        ),
    ]
